@startuml

package dao {


    interface UserDao{
        getUserByID(idUser : int): User
        getUserByEmail(mail : String): User
        User connectUser(mail : String,password : String )
        void registerUser(firstName : String, lastName : String, mail : String, password: String)
        boolean userExists(mail : String)
    }
    class UserDaoMySQL
    FactoryDao <|-- FactoryDaoSQL
    UserDao <|-- UserDaoMySQL

    abstract FactoryDao{
            + getFactory(type : String) : FactoryDao
            + getUserDao() : UserDAO
    }

    class FactoryDaoSQL{
    }
}
package business{
    class UserFacade{
        +login(mail : String, password : String) : Void
    }
    class User{
        -firstName : String
        -lastName : String
        -email : String
        -password : String
        +getFirstName() : String
        +getLastName() : String
        +getEmail() : String
        +getPassword() : String
        +setFirstName(name : String)
        +setLastName(lastName : String)
        +setEmail(email : String)
        +setPassword(password : String)
    }
    FactoryDao <--- UserFacade
    User <--Right- UserFacade
}

package gui{
    class LoadView
    package controller{
        class LoginController{
            + handleLogin(mail : String, password : String) : void
        }

    }
}
UserFacade <-- LoginController



@enduml