@startuml

package dao {


    abstract UserDao{
        getUserByEmail(mail : String): User
        userExists(email : String) : boolean
    }
    class UserDaoMySQL
    AbstractFactoryDao <|-- FactoryDaoSQL
    UserDao <|-- UserDaoMySQL

    abstract DAO<T>{
        find(id : int) : T
        create(T obj) : boolean
        update(T obj) : boolean
        delete(T obj) : boolean
    }

    abstract AbstractFactoryDao{
            + {static} getFactory(type : TypeDB) : AbstractFactoryDao
            + getUserDao() : UserDAO
    }

    class FactoryDaoSQL{
    }

    enum TypeDB{
        MySQL
        PostgreSQL
    }

    DAO <|-- UserDao
}
package db{
    class ConnectionDBMySQL{
        - connection : Connection
        - ConnectionDBMySQL()
        + {static} getInstance() : ConnectionDBMySQL
        + getDb() : Connection
    }
    class LazyHolderDB{
        + {static} final INSTANCE : ConnectionDBMySQL
    }
    interface ConnectionDB
    ConnectionDBMySQL -Left-> LazyHolderDB
    ConnectionDBMySQL .up.|> ConnectionDB

    ConnectionDB <-- DAO
}
package business{
    class UserFacade{
        + UserFacade()
        + login(mail : String, password : String) : Void
    }
    class User{
        -firstName : String
        -lastName : String
        -email : String
        -password : String
        + User()
        +getFirstName() : String
        +getLastName() : String
        +getEmail() : String
        +getPassword() : String
        +setFirstName(name : String)
        +setLastName(lastName : String)
        +setEmail(email : String)
        +setPassword(password : String)
        +checkPassword(password : String)
    }


    class Session{
        -user : User
        - Session()
        + {static} getInstance() : Session
        + getUser() : User
        + setUser(user : User) : User
    }
    class LazyHolderSession{
        + {static} final INSTANCE : Session
    }
    Session -Left-> LazyHolderSession
    Session --> User : -user

}

package gui{

    class LoadView{
        + {static} load(nameFxml : Parent) : Parent
        + {static} changeScreen(actionEvent : ActionEvent, view : String) : void
    }

    package controller{
        class LoginController{
            + handleLogin(mail : String, password : String) : void
        }

    }
}
UserFacade <-- LoginController



@enduml