@startuml
title Display an Offer Diagram

actor User
participant "ViewOffer (fxml)"
participant "Homepage (fxml)"
participant OfferController
participant OfferFacade
participant OfferDao
participant AbstractFactoryDAO
participant FactoryDAOMySQL
participant OfferDAOMySQL
participant Connection
participant Statement
database DB


"Homepage (fxml)"-->User: Display Homepage view

activate "Homepage (fxml)"
activate User
activate DB
activate Connection

User->"Homepage (fxml)":Select an offer to view(offerId : int)

"Homepage (fxml)"->OfferController: handleViewOffer(actionEvent : ActionEvent)

activate OfferController

OfferController->OfferFacade:getOffer(offerId : int)

deactivate OfferController

activate OfferFacade

OfferFacade->OfferDao : getInstance()
alt if (first getInstance)
    activate OfferDao
    OfferDao -> AbstractFactoryDAO : getInstance()
    activate AbstractFactoryDAO
    AbstractFactoryDAO --> OfferDao : FactoryDAOMySQL
    deactivate AbstractFactoryDAO

    OfferDao -> FactoryDAOMySQL : getOfferDao()
    activate FactoryDAOMySQL
    FactoryDAOMySQL -> OfferDAOMySQL **:Create(connection)
    activate OfferDAOMySQL
    FactoryDAOMySQL --> OfferDao : OfferDaoMySQL
    deactivate FactoryDAOMySQL
end
OfferDao --> OfferFacade : OfferDaoMySQL
deactivate OfferDao

deactivate FactoryDAOMySQL

OfferFacade->OfferDAOMySQL: find(offerId : int)

OfferDAOMySQL->Connection: prepareStatement()

Connection-->Statement **: Create

activate Statement

Connection-->OfferDAOMySQL: Statement


OfferDAOMySQL->Statement:executeQuery()

Statement->DB: SQL Query

DB->Statement:Result

Statement-->OfferDAOMySQL: ResultSet

deactivate Statement

OfferDAOMySQL-->OfferFacade: return new(Offer) : Offer

OfferFacade-->OfferController : return Offer
activate OfferController

deactivate OfferFacade
deactivate "Homepage (fxml)"

OfferController-->"ViewOffer (fxml)": Display the offer view
activate "ViewOffer (fxml)"

deactivate OfferController

"ViewOffer (fxml)"-->User: Display corresponding Offer
deactivate Connection
deactivate DB
deactivate User

@enduml