@startuml

package dao {


    interface OfferDao{
        getOffersFromUser(userId : int) : ArrayList<Offer>
        getOffersByCity(city : String) : ArrayList<Offer>
        getLatestOffers() : ArrayList<Offer>
        offerExists(id : int) : boolean
    }
    class OfferDaoMySQL
    FactoryDaoSQL .up.|> AbstractFactoryDao
    OfferDaoMySQL .up.|> OfferDao


    interface DAO<T>{
        find(id : int) : T
        create(T obj) : T
        update(T obj) : T
        delete(T obj) : boolean
    }

    abstract AbstractFactoryDao{
        - {static } final connectionDB : ConnectionDB
        + {static} getFactory(type : TypeDB) : AbstractFactoryDao
        + getOfferDao() : OfferDao
    }

    class FactoryDaoSQL{
    }


    DAO <|-- OfferDao
}
package db{
    class ConnectionDBMySQL{
        - connection : Connection
        - ConnectionDBMySQL()
        + {static} getInstance() : ConnectionDBMySQL
        + getDb() : Connection
    }

    class LazyHolderDB{
        + {static} final INSTANCE : ConnectionDBMySQL
    }
    interface ConnectionDB
    ConnectionDBMySQL -Left-> LazyHolderDB
    ConnectionDBMySQL .up.|> ConnectionDB

}
package business{
    class SessionFacade{
        + SessionFacade()
        + getUser() : User
    }

    class Offer{
        -offerId : int
        -title : String
        -pricePerDay : int
        -description : String
        -toolState : String
        -isPriority : boolean
        -userId : int
        -categoryId : int
        + Offer(String title,int price,String desc,String state,boolean isPriority,int userId,int categoryId)
        + getOfferId() : int
        + getTitle() : String
        + getPricePerDay() : int
        + getDescription() : String
        + getUserId() : int
        + getCategoryId() : int
        + setTitle(title:String) : void
        + setDescription(description:String) : void
        + setPricePerDay(price:int) : void
        + setUserId(userId:int) : void
        + setCategoryId(categoryId:int) : void
        + setIsPriority(b:boolean) : void
    }


    class OfferFacade{
        + OfferFacade()
        + getOffer(idOffer : int) : Offer
        + createOffer(idUser : int, title : String, description : String, state : String, Category : String, toSale : boolean...) : Offer
    }

}

package gui{

    class LoadView{
        + {static} load(nameFxml : Parent) : Parent
        + {static} changeScreen(actionEvent : ActionEvent, view : String) : void
    }

    package controller{
        class OfferController{
            + handleNewOffer(title : String, description : String, state : String, Category : String, toSale : boolean...) : void
            + handleViewOffer(offer : Offer) : void
        }

    }
}
OfferFacade <--Up- OfferController
SessionFacade <--Up- OfferFacade
OfferFacade .Up.> AbstractFactoryDao



@enduml