@startuml
title Create Offer Diagram

actor User
participant "CreateOffer (fxml)"
participant "ViewOffer (fxml)"
participant OfferController
participant OfferFacade
participant AbstractFactoryDAO
participant SessionFacade
participant ConnectionDBMySQL
participant FactoryDAOMySQL
participant OfferDAOMySQL
participant Connection
participant Statement
database DB


"CreateOffer (fxml)"-->User: Display the form to create an offer

activate "CreateOffer (fxml)"
activate User
activate DB
activate Connection
activate ConnectionDBMySQL
activate SessionFacade



User->"CreateOffer (fxml)":Enter the offer information (title : String, description : String, state : String, Category : String, city : String, price : int)

"CreateOffer (fxml)"->OfferController: handleNewOffer(actionEvent : ActionEvent)

deactivate "CreateOffer (fxml)"

activate OfferController

OfferController->OfferFacade:createOffer(title : String, description : String...)

activate OfferFacade

OfferFacade->AbstractFactoryDAO:getInstance()

activate AbstractFactoryDAO

AbstractFactoryDAO -> ConnectionDBMySQL : getInstance()

AbstractFactoryDAO <-- ConnectionDBMySQL : connectionDBMySQL

AbstractFactoryDAO--> OfferFacade : FactoryDAOMySQL

deactivate AbstractFactoryDAO

OfferFacade -> FactoryDAOMySQL:getOfferDAO()

activate FactoryDAOMySQL

FactoryDAOMySQL->OfferDAOMySQL **:Create(connection)

activate OfferDAOMySQL

FactoryDAOMySQL-->OfferFacade:OfferDAOMySQL

deactivate FactoryDAOMySQL

OfferFacade->SessionFacade: getUser()

SessionFacade-->OfferFacade: user

OfferFacade->OfferDAOMySQL: create(new Offer(userid : int, title : String, description : String...) : Offer)

OfferDAOMySQL->Connection: prepareStatement()

Connection-->Statement **: Create

activate Statement

Connection-->OfferDAOMySQL: Statement

OfferDAOMySQL->Statement:executeQuery()

Statement->DB: SQL Query

DB->Statement:Result

Statement-->OfferDAOMySQL: ResultSet

deactivate Statement

OfferDAOMySQL->OfferFacade: Offer(id : int, userid : int, title : String, description : String...)

deactivate OfferDAOMySQL


OfferFacade-->OfferController: offer : Offer

deactivate OfferFacade

OfferController-->"ViewOffer (fxml)": Display ViewOffer

deactivate OfferController

activate "ViewOffer (fxml)"

"ViewOffer (fxml)"-->User: Display corresponding View

deactivate SessionFacade
deactivate "ViewOffer (fxml)"
deactivate DB
deactivate User
deactivate ConnectionDBMySQL
deactivate Connection

@enduml