@startuml
title Favory Diagram

actor User
participant "Homepage (fxml)"
participant HomePageController
participant HomePageFacade
participant SessionFacade
participant AbstractFactoryDAO
participant FactoryDAOMySQL
participant FavoryDaoMySQL
participant Connection
participant Statement
database DB


"Homepage (fxml)"-->User: Display list offers offers

activate "Homepage (fxml)"
activate User
activate DB
activate SessionFacade
activate Connection

User->"Homepage (fxml)": fav on an offer

"Homepage (fxml)"-> HomePageController: handleFavOffer(actionEvent ActionEvent)

activate HomePageController

HomePageController->HomePageFacade: favOffer(offerID : int)



activate HomePageFacade

HomePageFacade->AbstractFactoryDAO:getInstance()
activate AbstractFactoryDAO


AbstractFactoryDAO--> HomePageFacade : FactoryDAOMySQL
deactivate AbstractFactoryDAO

HomePageFacade -> FactoryDAOMySQL:getScoreOfferDAO()

activate FactoryDAOMySQL

FactoryDAOMySQL->FavoryDaoMySQL **:Create(connection)

activate FavoryDaoMySQL
FactoryDAOMySQL-->HomePageFacade:FavoryDaoMySQL

deactivate FactoryDAOMySQL
HomePageFacade -> SessionFacade : getUser()
SessionFacade --> HomePageFacade : user
HomePageFacade->FavoryDaoMySQL: create(new Favory(offerID: int, userId : int))

FavoryDaoMySQL->Connection: prepareStatement()


Connection-->Statement **: Create

activate Statement

Connection-->FavoryDaoMySQL: Statement



FavoryDaoMySQL->Statement:executeQuery()

Statement->DB: SQL Query

DB->Statement:Result

Statement-->FavoryDaoMySQL: ResultSet

deactivate Statement

FavoryDaoMySQL-->HomePageFacade: return favory
deactivate FavoryDaoMySQL


HomePageFacade --> HomePageController : return favory




HomePageController-->"Homepage (fxml)": Display home page with offer in fav
"Homepage (fxml)" --> User : Display home page with offer in fav
deactivate HomePageFacade
deactivate DB
deactivate User

@enduml